# Generated by Django 5.0.3 on 2024-04-07 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_document_tracker', '0002_usercontract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='facebook',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='info',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='twitter',
        ),
    ]
