# Generated by Django 5.0.3 on 2024-04-10 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_document_tracker', '0003_rename_facebook_profile_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='extra_data',
        ),
        migrations.AddField(
            model_name='extradata',
            name='contract_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_document_tracker.contract'),
        ),
    ]
