# Generated by Django 5.0.3 on 2024-04-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_document_tracker', '0004_remove_contract_extra_data_extradata_contract_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='insurance_number',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='tax_number',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companytype',
            name='transcription',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contracttype',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
