# Generated by Django 5.0.3 on 2024-04-12 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_document_tracker', '0005_alter_agent_insurance_number_alter_agent_tax_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='agent',
            name='company_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_document_tracker.companytype'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='insurance_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='tax_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companytype',
            name='transcription',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='trading_platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_document_tracker.tradingplatform'),
        ),
        migrations.AlterField(
            model_name='contracttype',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='extradata',
            name='contract_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extra_data_model', to='web_document_tracker.contract'),
        ),
        migrations.AlterField(
            model_name='extradata',
            name='payment_term',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='extradata',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='extradata',
            name='registration_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
