# Generated by Django 5.0.3 on 2024-05-10 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_document_tracker', '0006_alter_agent_address_alter_agent_company_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingplatform',
            name='name_lower',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
