# Generated by Django 5.0.3 on 2024-05-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_document_tracker', '0007_tradingplatform_name_lower'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='company_name_lower',
            field=models.CharField(blank=True, max_length=67),
        ),
        migrations.AlterField(
            model_name='tradingplatform',
            name='name_lower',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
    ]
