# Generated by Django 5.0.3 on 2024-05-10 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_document_tracker', '0009_alter_agent_company_name_lower'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contract',
            table='web_document_tracker_contract',
        ),
    ]
