# Generated by Django 5.0.3 on 2024-05-10 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_document_tracker', '0010_alter_contract_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contract',
            table=None,
        ),
    ]
