# Generated by Django 5.0.3 on 2024-06-09 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_document_tracker', '0011_alter_contract_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extradata',
            name='contract_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_data_model', to='web_document_tracker.contract'),
        ),
        migrations.AlterField(
            model_name='extradata',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='extradata',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='extradata',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
